// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "2d98a439-4ffa-4164-9cc5-e30264a269dc";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float chargeBAT;
float dischargeBAT;
float sensorHUM;
float sensorPRES;
float sensorTEMP;
float tempBAT;
float voltageBAT;
float voltageUSB;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(chargeBAT, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(dischargeBAT, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sensorHUM, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sensorPRES, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(sensorTEMP, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tempBAT, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(voltageBAT, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(voltageUSB, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
